### PR TITLE
Fix overflow issue from #145

### PR DESCRIPTION
**Pull request by JesseRWeigel**
This fixes the problem from #145  by adding overflowY: 'hidden' to the outermost backdrop container. It still could use some testing on Android and iOS to make sure it doesn't cause any unintended issues.

### CODE REVIEW

**Comment by JesseRWeigel** [comment]
This stops the entire page from moving, but it doesn't stop the scrollbar from appearing briefly. To stop it from appearing on webkit browsers (including Electron) use the following CSS 
``` css
::-webkit-scrollbar {
    width: 0;
    background: transparent;
 }
```

**Comment by sodik82** [comment]
is there any way to add `::-webkit-scrollbar` style in RN?

**Comment by JesseRWeigel** [comment]
I added it to a css file in my app. I am using React Native Web.

**Comment by sodik82** [comment]
would you mind if I take only the one line from your PR? I believe it is only.

```
    overflowY: 'hidden',
```

the rest is just formatting, right?

**Comment by JesseRWeigel** [comment]
Sure! I am sorry. I didn't realize that I had changed the formatting.

**Comment by sodik82** [comment]
I have released 0.15.1 with your fix

**Pull request closed without merging**
