### PR TITLE
desktop platform added in 'makeTouchable`

### PR DESCRIPTION
**Pull request by vkjr**
I tried to use the project with [react-native-desktop](https://github.com/status-im/react-native-desktop) and in order to do this `desktop` platform should be added to `makeTouchable`.
Do you mind adding it?

Thanks,
Volodymyr.

### CODE REVIEW

**Comment by sodik82** [comment]
does `default` key works in react-native-desktop as well ? https://github.com/facebook/react-native/blob/d01ab66b47a173a62eef6261e2415f0619fefcbb/Libraries/Utilities/Platform.ios.js#L39

maybe we can "solve" this problem for all other (web, windows).

**Comment by vkjr** [comment]
Yes, it should work - https://github.com/status-im/react-native-desktop/blob/master/Libraries/Utilities/Platform.desktop.js#L17

**Comment by vkjr** [comment]
Done

**Comment by sodik82** [comment]
btw: does popup menu work fine in react-native-desktop?

**Comment by vkjr** [comment]
@sodik82, thanks for merging changes.
I did try only basic example and it worked fine :)

**Pull request merged**
