### PR TITLE
Add openAnimationDuration/closeAnimationDuration properties to Popover renderer

### PR DESCRIPTION
**Pull request by TheAlmightyBob**
We like everything about the Popover renderer except the animations. But rather than simply having an option to disable them, it seemed perhaps more flexible to allow customizing their durations.

@sodik82 I notice that this includes a lot of extra unrelated changes to `rnpm.js`, which appear to be simply reverting the extra unrelated changes that came along with #251.... I'm not sure what's expected here? I'm guessing there must be some kind of environmental difference between us causing this...

### CODE REVIEW

**Comment by sodik82** [comment]
looks good... thanks

**Comment by sodik82** [comment]
maybe someone will update TS definitions later on ;-)

**Comment by TheAlmightyBob** [comment]
@sodik82 Oh right. We've actually been using a custom types file with this library for so long that I forgot there _were_ TS definitions... hm

**Comment by TheAlmightyBob** [comment]
Yeah it doesn't look like the existing types really cover the different renderers... they're just declared like this

```typescript
  export const renderers: Readonly<{
    ContextMenu: Function;
    NotAnimatedContextMenu: Function;
    SlideInMenu: Function;
    Popover: Function;
  }>;
```

(but yes it would be nice if they were updated in general, it's just that there would be more to it than simply adding these two properties)

**Comment by sodik82** [comment]
TS definitions are maintained by community... so I am also not that familiar with that...

**Pull request merged**
